### PR TITLE
 Update Android Env to version 2.18.162

### PR DESCRIPTION
**Pull request by punneetmehta**
Updated Version & MD5 Classes Hash

### CODE REVIEW

**Comment by pabloruan0710** [comment]
This Env return 

> INFO:yowsup.common.http.warequest:{"login":"556295004777","status":"fail","reason":"old_version"} 

`
 yowsup-cli registration --register 376661 --phone 55******* --cc 55`

**Comment by punneetmehta** [comment]
@pabloruan0710 
Use -E android

`yowsup-cli registration -E android -r sms --cc 91 --phone 91XXXXXXXXXX`

> yowsup-cli  v2.0.15
> yowsup      v2.5.7
> 
> Copyright (c) 2012-2016 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> INFO:yowsup.common.http.warequest:b'{"login":"91xxxxxxxxxx","status":"sent","length":6,"method":"sms","retry_after":14405,"sms_wait":14405,"voice_wait":65}\n'

**Comment by pabloruan0710** [comment]
I'm using -E android, the sms is sent but not register code, I received old_version

**Comment by punneetmehta** [comment]
@pabloruan0710 
Working fine for Me.
and If there is **old_version** issue, you'll not get the sms.
You will get same **old_version** error while **requesting code** too.

`yowsup-cli registration -E android -R 778940 --cc 91 --phone 91XXXXXXXXXX`

> yowsup-cli  v2.0.15
> yowsup      v2.5.7
> 
> Copyright (c) 2012-2016 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> 
> INFO:yowsup.common.http.warequest:b'{"status":"ok","login":"91XXXXXXXXXX","type":"existing","edge_routing_info":"CAA=","chat_dns_domain":"sl","pw":"PASSWORD","expiration":4444444444.0,"kind":"free","price":"$0.99","cost":"0.99","currency":"USD","price_expiration":1528131604}\n'
> price: b'$0.99'
> login: b'91XXXXXXXXXX'
> currency: b'USD'
> pw: b'PASSWORD'
> cost: b'0.99'
> kind: b'free'
> expiration: 4444444444.0
> price_expiration: 1528131604
> type: b'existing'
> status: b'ok'

**Pull request merged**
