### PR TITLE
Fix send video message

### PR DESCRIPTION
**Pull request by fmachadodev**
Now it is possible to send video messages using protobuf (only on python3 + and depends on pyAV lib https://github.com/mikeboers/PyAV)

### CODE REVIEW

**Comment by mikesalmonuk** [comment]
Based off your awesome work done here @fmachadodev, do you know how easy it'll be to add audio sending as well, assuming video and audio are fairly similar media types to send (i think, without digging too deep into the code).

**Comment by fmachadodev** [comment]
@mikesalmonuk , I will implement audio sending too, but before, I need to dig a bit more in video sending. Sometimes the receiver can`t download the video message, (and I realize just now, after sending the pull request).

thanks

**Comment by AragurDEV** [comment]
Hey thanks a lot, nice work done.

**Comment by xwanyiri** [comment]
You guys are Awesum!

**Pull request merged**
